### ISSUE TITLE
What versions of Node are supported?

### ISSUE THREAD

**Issue by alebelcor** [olegskl/gulp-stylelint#11]
Looking at the code it would seem that it's Node v4+ but I'm not 100% sure. It's also missing in the `package.json` file.

**Comment by olegskl** [comment]
The code is written in ES6 with `import` statements that Node does not support yet. When you install a published package from npm, you get a babelified version which works on Node 0.12+. Travis builds are run on Node 0.12, 4, and 5. See [.travis.yml](https://github.com/olegskl/gulp-stylelint/blob/master/.travis.yml).

**Comment by alebelcor** [comment]
Huh, I'm on `0.12.13` and it's failing for me.

The problem seems to be `Object.assign` is not being transpiled into anything ES5.

Doing a quick check in the Node REPL indicates that `Object.assign` is `undefined`, so maybe that's it.

It's weird that the build doesn't fail because of it.

**Comment by olegskl** [comment]
Thanks for reporting this. Will be fixed soon.

**Comment by olegskl** [comment]
The reason why it didn't fail during Travis builds is because of [babel-tape-runner](https://github.com/wavded/babel-tape-runner) which [polyfills](https://github.com/wavded/babel-tape-runner/blob/master/bin/babel-tape-runner#L4) everything... so missing features like `Object.assign` are available while running tests. Bummer.

I'm closing this issue, but feel free to reopen it if the fix doesn't work for you. Thanks again for reporting the issue, much appreciated!
