### ISSUE TITLE
Permanent TypeError in version 3.2.0

### ISSUE THREAD

**Issue by bitxo** [olegskl/gulp-stylelint#43]
I had to go to versión 2.0.2 because I get an error with version 3.2.0 executing the gulp task with no other change.

TypeError: undefined is not a function at Object.<anonymous> (...\node_modules\gulp-stylelint\node_modules\stylelint\node_modules\postcss-media-query-parser\dist\nodes\Container.js:38:30) at Module._compile (module.js:460:26) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Module.require (module.js:365:17) at require (module.js:384:17) at Object.<anonymous> (...\node_modules\gulp-stylelint\node_modules\stylelint\node_modules\postcss-media-query-parser\dist\index.js:8:18) at Module._compile (module.js:460:26) at Object.Module._extensions..js (module.js:478:10)

**Comment by olegskl** [comment]
Thank you for taking your time to report this. Having read the error message I believe that the issue is not in gulp-stylelint but in [postcss-media-query-parser](https://github.com/dryoma/postcss-media-query-parser) that you're using. I'm also assuming that you're running an old version of Node. I have opened a **[pull request](https://github.com/dryoma/postcss-media-query-parser/pull/5)** that should fix the issue in postcss-media-query-parser.

**Comment by olegskl** [comment]
A new version of postcss-media-query-parser **[has been released](https://github.com/dryoma/postcss-media-query-parser/releases/tag/0.2.1)**. Please update your dependencies and try to run gulp-stylelint 3.2.0 again.

**Comment by bitxo** [comment]
ok, thanks for advice, I'll try what you suggest :) thank you :)

**Comment by bitxo** [comment]
as you said, now it works :) thanks a lot :)

**Comment by olegskl** [comment]
Awesome ;)
